### ISSUE TITLE
您好，请问一下进行Overlapped Cluster后，正负结点是如何选定的

### ISSUE THREAD

**Issue by marsh312** [CSHaitao/JTR#2]
利用KMeans初始化得到的树中，一个document仅仅被分配给了一个leaf node，这个时候正节点是document对应的leaf node及其祖先，其余为负结点，树的每一层仅有一个正节点；
而在进行一个Overlapped Cluster后，一个document被分配给了多个leaf node，此时树的每一层将会有多个正节点，那这个时候是怎么选取正负节点，以适应新的cluster assignment的？

在您的`JTR/reorganize_clusters_tree.py`源码中，有如下代码，如果我的理解没有出错，您在更新cluster后，`dict_label`直接取成了`pid`所对应的最后一个节点的label，即只考虑document被分配到的最后一个leaf node，而之前被分配的leaf node直接不考虑？这样的话，似乎不能适应新的cluster assignment。这是我的一点浅薄的理解，如果有错误，烦请您指出，我将感激不尽！
```python
    dict_label = {}   
    for leaf in tree.leaf_dict:
        node = tree.leaf_dict[leaf]
        pids = node.pids
       
        for pid in pids:
            dict_label[pid] = str(node.val)
```

**Comment by CSHaitao** [comment]
是的，训练时可以改进一下，目前有一些损失函数可以多个正例，或者对所有正例都采样训练一下～～

**Comment by marsh312** [comment]
> 是的，训练时可以改进一下，目前有一些损失函数可以多个正例，或者对所有正例都采样训练一下～～

但这样会不会存在如下问题，比如考虑这样一种极端情况，overlapped cluster后，一个document对应了多个leaf node，它们的祖先构成的集合包含了某一层的所有树节点，这样该level上就只有正样本节点，没有负样本了。

**Comment by CSHaitao** [comment]
如果出现这种情况在这一层选哪个节点都可以了，在剪枝时候都无所谓了

**Comment by marsh312** [comment]
> 如果出现这种情况在这一层选哪个节点都可以了，在剪枝时候都无所谓了

指的是在这一层不选负样本，还是随便选一个节点作为负样本呢？

**Comment by CSHaitao** [comment]
这个查询可以不在这一层训练

**Comment by marsh312** [comment]
> 这个查询可以不在这一层训练

好的，感谢您的回答
